fix: Seperating child ChangeHighLight components from their parents
medhatdawoud/react-change-highlight pull request #10
Opened 2019-11-10 09:38 UTC by EslamHiko

This PR is meant to fix : https://github.com/medhatdawoud/react-change-highlight/issues/8

The code I'm using :

![code](https://user-images.githubusercontent.com/18349358/68541922-3cf36b80-03ae-11ea-8ba0-2f3a67c60f27.PNG)

Before : 

![before](https://user-images.githubusercontent.com/18349358/68541925-4250b600-03ae-11ea-997a-e08655c933ce.gif)

After : 

![after](https://user-images.githubusercontent.com/18349358/68541927-47156a00-03ae-11ea-9318-70ad6df85727.gif)

2019-11-11 20:23 UTC, medhatdawoud requested changes
I guess your solution is quite good, I just need you to try out giving a custom `highlightStyle` for each of the instances of `ChangeHighlight` and see if it's still get separated as well, and add the gif into the PR again, thanks for contribution

2019-11-11 20:23 UTC, medhatdawoud commented on src/ChangeHighlight.tsx
> +  const uniqueId = Math.floor(Math.random() * 100000)+1;
move this inside the useEffect condition of the first mount, because this will be called everytime

2019-11-11 20:23 UTC, medhatdawoud commented on src/ShadowChild.tsx
> +  elementDOM.setAttribute('react-change-hightlight-uniqueId',uniqueId);
you can name it a bit shorter as the default class name `rc-highlight-id` which make it simple and we recogise it as the uniqueId of course

2019-11-11 20:23 UTC, medhatdawoud commented on src/Util/setHighlight.ts
> +  if (!isInitial && element && element.getAttribute('react-change-hightlight-uniqueId') == uniqueId) {
use `===` not `==` for comparison, and I prefer to add the attribute name as a const in the consts file and `consts.ts` file and use it, better and easier for maintenance

2019-11-11 21:06 UTC, EslamHiko commented
Done 😄.

![after2](https://user-images.githubusercontent.com/18349358/68621219-d36f7c00-04d7-11ea-9e7d-6083a7f1e4bf.gif)


/cc @medhatdawoud

2019-11-12 00:09 UTC, medhatdawoud requested changes

2019-11-12 00:09 UTC, medhatdawoud commented on src/consts.ts
> +  HIGHLIGHT_UNIQUEID: "rc-highlight-id"
`HIGHLIGHT_UNIQUE_ID`

2019-11-12 04:08 UTC, EslamHiko commented on src/consts.ts
> +  HIGHLIGHT_UNIQUEID: "rc-highlight-id"
@medhatdawoud Done.

2019-11-12 09:40 UTC, merged

2019-11-12 09:41 UTC, medhatdawoud commented
@allcontributers add @EslamHiko for code

2019-11-12 09:43 UTC, medhatdawoud commented
@all-contributors add @EslamHiko for code