perf: separate generatingUUID logic & making it more complex
medhatdawoud/react-change-highlight pull request #15
Opened 2019-11-13 08:37 UTC by EslamHiko

This is a PR to fix: https://github.com/medhatdawoud/react-change-highlight/issues/8

![uuid](https://user-images.githubusercontent.com/18349358/68746523-6fe16d80-0601-11ea-9854-bd8a0bfeac54.PNG)

2019-11-15 00:22 UTC, medhatdawoud requested changes

2019-11-15 00:22 UTC, medhatdawoud commented on src/Util/generateUUID.ts
> +    var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
It seems to be less chances of having a duplicate id but it's ok, I'm fine with using bitwise despite I don't find a big benefit of using it here, just needs some cleaning to be kind of this:

```js
const randomNum = Math.random() * 16 | 0
const finalChar = c === 'x' ? randomNum : (randomNum & 0x3 | 0x8);
```

2019-11-15 00:22 UTC, medhatdawoud commented on src/ChangeHighlight.tsx
> +        setUniqueId(generateUUID());
I prefer to change the function name to have the proper verb, so it's more convenient to have `get` in the beginning, something like this `getUUID()`

2019-11-15 00:30 UTC, medhatdawoud commented on src/Util/setHighlight.ts
> +  if (!isInitial && element && element.getAttribute(defaults.HIGHLIGHT_UNIQUE_ID) === uniqueId) {
I'v updated the version of typescript to `3.7.2` which has the optional chaining, so this like could be as follow
```js
if (!isInitial && element?.getAttribute(defaults.HIGHLIGHT_UNIQUE_ID) === uniqueId) {
```

2019-11-17 14:19 UTC, medhatdawoud approved these changes

2019-11-17 14:20 UTC, merged

2020-10-07 11:58 UTC, EslamHiko commented
@medhatdawoud I would like to thank you so much for your content and I'll take your advice into action now, I'm looking for a job,  So can we have a small conversation about my skills & experience, and hopefully convince you to refer me to a good position?

2020-10-08 00:12 UTC, medhatdawoud commented
@EslamHiko Thanks for your contribution, let's move that chat to be on twitter, send me a DM @med7atdawoud